
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete
spec:
  selector:
    matchLabels:
      app: delete
  template:
    metadata:
      labels:
        app: delete
    spec:
#      priorityClassName: high-priority

      hostNetwork: true
      dnsPolicy: ClusterFirst               
      containers:        
        - image: aldemirn/delete
          name: delete
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"